# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

cloudnative_pg_helm_release_name: cloudnative-pg
cloudnative_pg_helm_chart_path: "../../charts/cloudnative-pg/"
cloudnative_pg_helm_chart_ref: /usr/local/src/cloudnative-pg

cloudnative_pg_helm_release_namespace: openstack
cloudnative_pg_helm_kubeconfig: "{{ kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"
cloudnative_pg_helm_values: {}

cloudnative_pg_barman_cloud_helm_release_name: cloudnative-pg-barman-cloud
cloudnative_pg_barman_cloud_helm_chart_path: "../../charts/plugin-barman-cloud/"
cloudnative_pg_barman_cloud_helm_chart_ref: /usr/local/src/plugin-barman-cloud

cloudnative_pg_barman_cloud_helm_release_namespace: openstack
cloudnative_pg_barman_cloud_helm_kubeconfig: "{{ kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"
cloudnative_pg_barman_cloud_helm_values: {}

cloudnative_pg_kubectl_plugin_version: "{{ atmosphere_images['cloudnative_pg'] | vexxhost.kubernetes.docker_image('tag') }}"

cloudnative_pg_kubectl_plugin_checksums:
  x86_64:
    1.30.0: 33784dc3b61edb0ddb1a68db6ef045bd32daace5db2ec1f0a02e0e8185eef7eb
  arm64:
    1.30.0: 633eec5eb13ec640284804338e64c09d3bdbf907734675dea9e30689eb77654a

cloudnative_pg_kubectl_plugin_download_url: "https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v{{ cloudnative_pg_kubectl_plugin_version }}/kubectl-cnpg_{{ cloudnative_pg_kubectl_plugin_version }}_{{ ansible_facts['system'] | lower }}_{{ cloudnative_pg_kubectl_plugin_artifact_goarch }}.tar.gz" # noqa: yaml[line-length]
cloudnative_pg_kubectl_plugin_download_dest: "{{ download_artifact_work_directory }}/cloudnative_pg_kubectl_plugin-{{ cloudnative_pg_kubectl_plugin_version }}-{{ ansible_facts['system'] | lower }}-{{ cloudnative_pg_kubectl_plugin_artifact_goarch }}.tar.gz" # noqa: yaml[line-length]
cloudnative_pg_kubectl_plugin_archive_checksum: "{{ cloudnative_pg_kubectl_plugin_checksums[cloudnative_pg_kubectl_plugin_artifact_goarch][cloudnative_pg_kubectl_plugin_version] }}"
