# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

hpe_nimble_csi_helm_kubeconfig: "{{ kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"

# HPE CSI driver Helm chart version
hpe_nimble_csi_helm_chart_version: "3.1.0"

# HPE CSI driver Helm chart repository
hpe_nimble_csi_helm_chart_repo: "https://hpe-storage.github.io/co-deployments/"
