# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

hpe_nimble_csi_helm_release_name: hpe-csi-driver
hpe_nimble_csi_helm_chart_path: "../../charts/hpe-csi-driver/"
hpe_nimble_csi_helm_chart_ref: /usr/local/src/hpe-csi-driver

hpe_nimble_csi_helm_release_namespace: kube-system
hpe_nimble_csi_helm_kubeconfig: "{{ kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"
hpe_nimble_csi_helm_values: {}
