#!/bin/sh

# NOTE(mnaser): The Molecule image does not ship with any build packages and it
#               does not use Alpine-shipped Python, this is a gross workaround
#               to avoid building `netifaces`.
if [ -e /etc/alpine-release ]; then
  apk add py3-netifaces
  ln -s \
    /usr/lib/python3.9/site-packages/netifaces-0.11.0-py3.9.egg-info \
    /usr/local/lib/python3.9/site-packages/netifaces-0.11.0-py3.9.egg-info
  ln -s \
    /usr/lib/python3.9/site-packages/netifaces.cpython-39-x86_64-linux-musl.so \
    /usr/local/lib/python3.9/site-packages/netifaces.cpython-39-x86_64-linux-musl.so
fi

# Install OpenStack SDK
pip install 'openstacksdk<0.99.0'
