# Copyright (c) 2022 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

_tempest_full_service_availability:
  cinder: true
  glance: true
  horizon: true
  neutron: true
  nova: true
  swift: true

_tempest_ci_service_availability:
  barbican: "{{ 'barbican' in tempest_ci_components }}"
  cinder: "{{ 'cinder' in tempest_ci_components }}"
  glance: "{{ 'glance' in tempest_ci_components }}"
  heat: "{{ 'heat' in tempest_ci_components }}"
  horizon: "{{ 'horizon' in tempest_ci_components }}"
  load_balancer: "{{ 'octavia' in tempest_ci_components }}"
  magnum: "{{ 'magnum' in tempest_ci_components }}"
  manila: "{{ 'manila' in tempest_ci_components }}"
  neutron: "{{ 'neutron' in tempest_ci_components }}"
  nova: "{{ 'nova' in tempest_ci_components }}"
  placement: "{{ 'placement' in tempest_ci_components }}"
  swift: false

_tempest_ci_test_patterns: >-
  {{
    tempest_ci_test_patterns
    if tempest_ci_mode == 'selective'
    else []
  }}

_tempest_ci_test_regex: >-
  {{
    '('
    ~ (_tempest_ci_test_patterns | join('|'))
    ~ ').*\[.*\bsmoke\b.*\]'
    if _tempest_ci_test_patterns | length > 0
    else ''
  }}

_tempest_helm_values:
  endpoints: "{{ openstack_helm_endpoints | combine(_tempest_endpoint_values, recursive=True) }}"
  images:
    tags: "{{ atmosphere_images | vexxhost.atmosphere.openstack_helm_image_tags('tempest') }}"
  manifests:
    certificates: "{{ tempest_cluster_issuer_ca_enabled | bool }}"
  tls:
    identity_ca_only: "{{ tempest_cluster_issuer_ca_enabled | bool }}"
  jobs:
    run_tests:
      restartPolicy: Never
      backoffLimit: 0
  pod:
    labels:
      include_app_kubernetes_io: false
  conf:
    script: >-
      tempest run --config-file /etc/tempest/tempest.conf -w 4{{
        ' --regex ' ~ (_tempest_ci_test_regex | quote)
        if _tempest_ci_test_regex | length > 0
        else ' --smoke'
      }}
    tempest:
      service_available: >-
        {{
          _tempest_full_service_availability
          | combine(
              _tempest_ci_service_availability
              if tempest_ci_mode == 'selective'
              else {}
            )
        }}
      compute:
        endpoint_type: internal
        fixed_network_name: public
      dashboard:
        dashboard_url: "https://{{ openstack_helm_endpoints_horizon_api_host }}"
        disable_ssl_certificate_validation: false
      identity:
        v3_endpoint_type: internal
      image:
        disk_formats: aki,ari,qcow2,raw
        endpoint_type: internal
      load_balancer:
        endpoint_type: internal
        enable_security_groups: true
      network:
        endpoint_type: internal
        floating_network_name: public
        shared_physical_network: false
      network-feature-enabled:
        port_security: true
      placement:
        endpoint_type: internal
      validation:
        image_ssh_user: cirros
      volume:
        endpoint_type: internal
        storage_protocol: ceph
      volume-feature-enabled:
        backup: false
      object-storage:
        build_timeout: 60
        endpoint_type: internal
        reseller_admin_role: admin
  secrets:
    tls:
      identity:
        api:
          internal: "{{ tempest_cluster_issuer_ca_secret_name }}"
  pvc:
    enabled: false

_tempest_endpoint_values:
  identity:
    auth:
      tempest:
        region_name: "{{ openstack_helm_endpoints_tempest_region_name }}"
        username: "tempest-{{ openstack_helm_endpoints_tempest_region_name }}"
        password: "{{ openstack_helm_endpoints_tempest_keystone_password }}"
    path:
      # NOTE(mnaser): Heat uses the catalog and blindly adds a /v3 to the end of
      #               the endpoint.  This is a workaround to make it work.
      default: /v3

_tempest_network_backend_settings:
  openvswitch:
    conf:
      tempest:
        network-feature-enabled:
          api_extensions:
            - address-scope
            - agent
            - allowed-address-pairs
            - auto-allocated-topology
            - availability_zone
            - binding
            - default-subnetpools
            - dhcp_agent_scheduler
            - dvr
            - ext-gw-mode
            - external-net
            - extra_dhcp_opt
            - extraroute
            - flavors
            - l3_agent_scheduler
            - l3-flavors
            - l3-ha
            - multi-provider
            - net-mtu
            - network_availability_zone
            - network-ip-availability
            - pagination
            - port-security
            - project-id
            - provider
            - qos
            - qos-bw-limit-direction
            - qos-bw-minimum-ingress
            - qos-default
            - qos-fip
            - qos-gateway-ip
            - qos-port-network-policy
            - qos-pps
            - qos-pps-minimum
            - qos-pps-minimum-rule-alias
            - qos-rule-type-details
            - qos-rule-type-filter
            - qos-rules-alias
            - qos-specs
            - quotas
            - rbac-policies
            - router
            - router_availability_zone
            - security-group
            - service-type
            - sorting
            - standard-attr-description
            - standard-attr-revisions
            - standard-attr-tag
            - standard-attr-timestamp
            - subnet_allocation
            - subnet-service-types
            - tag
            - trunk
            - trunk-details
  ovn:
    conf:
      tempest:
        network-feature-enabled:
          api_extensions:
            - address-scope
            - agent
            - allowed-address-pairs
            - auto-allocated-topology
            - availability_zone
            - binding
            - default-subnetpools
            - ext-gw-mode
            - external-net
            - extra_dhcp_opt
            - extraroute
            - flavors
            - l3-flavors
            - l3-ha
            - multi-provider
            - net-mtu
            - network_availability_zone
            - network-ip-availability
            - pagination
            - port-security
            - project-id
            - provider
            - qos
            - qos-bw-limit-direction
            - qos-bw-minimum-ingress
            - qos-default
            - qos-fip
            - qos-gateway-ip
            - qos-port-network-policy
            - qos-pps
            - qos-pps-minimum
            - qos-pps-minimum-rule-alias
            - qos-rule-type-details
            - qos-rule-type-filter
            - qos-rules-alias
            - qos-specs
            - quotas
            - rbac-policies
            - router
            - router_availability_zone
            - security-group
            - service-type
            - sorting
            - standard-attr-description
            - standard-attr-revisions
            - standard-attr-tag
            - standard-attr-timestamp
            - subnet_allocation
            - subnet-service-types
            - tag
            - trunk
            - trunk-details
            - vpnaas
            - vpn-endpoint-groups
