---
# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

smartctl_exporter_helm_release_name: prometheus-smartctl-exporter
smartctl_exporter_helm_chart_path: "../../charts/prometheus-smartctl-exporter/"
smartctl_exporter_helm_chart_ref: /usr/local/src/prometheus-smartctl-exporter

smartctl_exporter_helm_release_namespace: monitoring
smartctl_exporter_helm_kubeconfig: "{{ kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"
smartctl_exporter_helm_values: {}
