---
# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: smartctl_exporter_smartctl_device_exclude [[[
#
# Regular expression of devices to exclude from SMART monitoring.
#
# .. code-block:: yaml
#    :linenos:
#
#    smartctl_exporter_smartctl_device_exclude: ""
#
smartctl_exporter_smartctl_device_exclude: ""
                                                                    # ]]]
