# Copyright (c) 2026 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Deploy Keycloak Operator
  ansible.builtin.import_tasks: operator.yml

- name: Deploy Keycloak database
  ansible.builtin.import_tasks: database.yml

- name: Migrate Keycloak database
  ansible.builtin.import_tasks: database_migration.yml

- name: Deploy Keycloak instance
  ansible.builtin.import_tasks: instance.yml
