VERSION 0.7

ARG --global SERIES=3.1
ARG --global VERSION=3.1.0-65

platform-image:
  FROM quay.io/centos/centos:stream9
  LABEL org.opencontainers.image.source=https://github.com/vexxhost/atmosphere
  DO ../+DNF_INSTALL --PACKAGES "centos-release-nfv-openvswitch.noarch"
  DO ../+DNF_INSTALL --PACKAGES "openvswitch${SERIES}-${VERSION}.el9s iptables"
  SAVE IMAGE --push \
    ghcr.io/vexxhost/atmosphere/openvswitch:${SERIES} \
    ghcr.io/vexxhost/atmosphere/openvswitch:${VERSION}

image:
  BUILD --platform linux/amd64 --platform linux/arm64 +platform-image
