VERSION 0.7

image:
  ARG CLOUD_ARCHIVE_RELEASE
  FROM ../cloud-archive-base+image --CLOUD_ARCHIVE_RELEASE=${CLOUD_ARCHIVE_RELEASE}
  ENV DEBIAN_FRONTEND=noninteractive
  DO ../+APT_INSTALL --PACKAGES "\
    build-essential \
    crudini \
    curl \
    git \
    libssl-dev \
    libpcre3-dev \
    lsb-release \
    openssh-client \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv"
  RUN --mount type=cache,target=/root/.cache \
    python3 -m venv --upgrade --system-site-packages /var/lib/openstack
  ENV UWSGI_PROFILE_OVERRIDE=ssl=true
  RUN --mount type=cache,target=/root/.cache \
    mkdir -p /wheels && \
    /var/lib/openstack/bin/pip3 wheel --wheel-dir /wheels uwsgi
