VERSION 0.7

ARG --global PROJECT=nova
ARG --global RELEASE=zed
ARG --global PROJECT_REF=3d1a705fc85a0f0a46e7cbc322e98fff892e21b8

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF}

platform-image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  DO ../+APT_INSTALL \
    --PACKAGES "ceph-common genisoimage iproute2 libosinfo-bin lsscsi ndctl nvme-cli openssh-client ovmf python3-libvirt python3-rados python3-rbd qemu-efi-aarch64 qemu-utils sysfsutils udev util-linux"
  GIT CLONE --branch v1.4.0 https://github.com/novnc/noVNC.git /usr/share/novnc
  ARG REGISTRY=ghcr.io/vexxhost/atmosphere
  SAVE IMAGE --push \
    ${REGISTRY}/${PROJECT}:${RELEASE} \
    ${REGISTRY}/${PROJECT}:${PROJECT_REF}

image:
  BUILD --platform linux/amd64 --platform linux/arm64 +platform-image
