VERSION 0.7

ARG --global PROJECT=nova
ARG --global RELEASE=zed
ARG --global PROJECT_REF=226f3e95c1cdadd1845c7adee55f5c5f29f3a7a8

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF}

platform-image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  DO ../+APT_INSTALL \
    --PACKAGES "ceph-common genisoimage iproute2 libosinfo-bin lsscsi ndctl nvme-cli openssh-client ovmf python3-libvirt python3-rados python3-rbd qemu-efi-aarch64 qemu-utils sysfsutils udev util-linux"
  GIT CLONE --branch v1.4.0 https://github.com/novnc/noVNC.git /usr/share/novnc
  SAVE IMAGE --push \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${RELEASE} \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${PROJECT_REF}

image:
  BUILD --platform linux/amd64 --platform linux/arm64 +platform-image
