VERSION 0.7

image:
  FROM aquasec/trivy:0.48.3
  COPY .trivyignore /.trivyignore
  # TODO(mnaser): Add automatic updates
  RUN trivy image --download-db-only
  RUN trivy image --download-java-db-only
