VERSION 0.7

ARG --global PROJECT=tempest
ARG --global RELEASE=master
ARG --global PROJECT_REF=699749ec27897efe9bd7824664237c16c3339c03

build.plugin:
  ARG PLUGIN
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+GIT_CHECKOUT \
    --PROJECT=${PLUGIN} \
    --PROJECT_REF=${RELEASE}
  SAVE ARTIFACT /src

octavia-test-server:
  FROM golang:1.21
  COPY (+build.plugin/src --PLUGIN=octavia-tempest-plugin) /src
  ENV GO111MODULE=off
  ENV CGO_ENABLED=0
  ENV GOOS=linux
  RUN go build \
    -a -ldflags '-s -w -extldflags -static' \
    -o /build/test_server.bin \
    /src/octavia_tempest_plugin/contrib/test_server/test_server.go
  SAVE ARTIFACT /build/test_server.bin

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  COPY (+build.plugin/src --PLUGIN=barbican-tempest-plugin) /barbican-tempest-plugin
  COPY (+build.plugin/src --PLUGIN=cinder-tempest-plugin) /cinder-tempest-plugin
  COPY (+build.plugin/src --PLUGIN=heat-tempest-plugin) /heat-tempest-plugin
  COPY (+build.plugin/src --PLUGIN=keystone-tempest-plugin) /keystone-tempest-plugin
  COPY (+build.plugin/src --PLUGIN=neutron-tempest-plugin) /neutron-tempest-plugin
  COPY (+build.plugin/src --PLUGIN=octavia-tempest-plugin) /octavia-tempest-plugin
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF} \
    --PIP_PACKAGES="/barbican-tempest-plugin /cinder-tempest-plugin /heat-tempest-plugin /keystone-tempest-plugin /neutron-tempest-plugin /octavia-tempest-plugin junitxml"

image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +octavia-test-server/test_server.bin /opt/octavia-tempest-plugin/test_server.bin
  COPY +build/venv /var/lib/openstack
  DO ../+APT_INSTALL \
    --PACKAGES "iputils-ping openssh-client"
  ARG REGISTRY=ghcr.io/vexxhost/atmosphere
  SAVE IMAGE --push \
    ${REGISTRY}/${PROJECT}:${RELEASE} \
    ${REGISTRY}/${PROJECT}:${PROJECT_REF}
