VERSION 0.7

ARG --global SERIES=23.03
ARG --global VERSION=23.03.0-69
ARG --global PROJECT_REF=5359e7d7f872058b6e5bf884c9f19d1922451f29

ovn-kubernetes:
  FROM --platform=linux/amd64 golang:1.20
  GIT CLONE --branch ${PROJECT_REF} https://github.com/ovn-org/ovn-kubernetes /src
  WORKDIR /src
  COPY patches/ovn-kubernetes /patches
  DO ../+APT_INSTALL --PACKAGES "git"
  RUN git apply --verbose /patches/*.patch
  SAVE ARTIFACT /src/dist/images/ovndb-raft-functions.sh
  SAVE ARTIFACT /src/dist/images/ovnkube.sh
  ARG GOOS=linux
  ARG GOARCH=amd64
  RUN \
    cd /src/go-controller && \
    go build -o /build/ovn-kube-util ./cmd/ovn-kube-util
  SAVE ARTIFACT /build/ovn-kube-util

component-image:
  FROM ../openvswitch+platform-image
  DO ../+DNF_INSTALL --PACKAGES "firewalld-filesystem hostname ovn${SERIES}-${VERSION}.el9s procps-ng"
  ARG --required NAME
  DO ../+DNF_INSTALL --PACKAGES "ovn${SERIES}-${NAME}-${VERSION}.el9s"
  COPY ../kubernetes+image/kubectl /usr/local/bin/kubectl
  COPY +ovn-kubernetes/ovndb-raft-functions.sh /root
  COPY +ovn-kubernetes/ovnkube.sh /root
  ARG TARGETARCH
  ARG TARGETVARIANT
  COPY (+ovn-kubernetes/ovn-kube-util --GOARCH=$TARGETARCH --VARIANT=$TARGETVARIANT) /usr/bin
  ARG REGISTRY=ghcr.io/vexxhost/atmosphere
  SAVE IMAGE --push \
    ${REGISTRY}/ovn-${NAME}:${SERIES} \
    ${REGISTRY}/ovn-${NAME}:${VERSION}

central:
  BUILD +component-image --NAME central

host:
  BUILD +component-image --NAME host

images:
  BUILD +central
  BUILD --platform linux/amd64 --platform linux/arm64 +host
