VERSION 0.7

ARG --global REGISTRY=ghcr.io/vexxhost/atmosphere
ARG --global SERIES=23.03
ARG --global VERSION=23.03.0-69

component-image:
  FROM ../openvswitch+platform-image
  DO ../+DNF_INSTALL --PACKAGES "firewalld-filesystem hostname ovn${SERIES}-${VERSION}.el9s procps-ng"
  ARG --required NAME
  DO ../+DNF_INSTALL --PACKAGES "ovn${SERIES}-${NAME}-${VERSION}.el9s"
  IF [ "${NAME}" = "host" ]
    COPY ../kubernetes+image/kubectl /usr/local/bin/kubectl
  END
  SAVE IMAGE --push \
    ${REGISTRY}/ovn-${NAME}:${SERIES} \
    ${REGISTRY}/ovn-${NAME}:${VERSION}

central:
  BUILD +component-image --NAME central

host:
  BUILD +component-image --NAME host

images:
  BUILD +central
  BUILD --platform linux/amd64 --platform linux/arm64 +host
