# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Create an ImageCatalog
  run_once: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: postgresql.cnpg.io/v1
      kind: ImageCatalog
      metadata:
        name: postgresql
        namespace: openstack
      spec: "{{ _cloudnative_pg_cluster_image_catalog_spec | combine(cloudnative_pg_cluster_image_catalog_spec, recursive=True) }}"

- name: Apply CloudNativePG cluster
  run_once: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: cnpg-db
        namespace: openstack
      spec: "{{ _cloudnative_pg_cluster_spec | combine(cloudnative_pg_cluster_spec, recursive=True) }}"
    wait_sleep: 1
    wait_timeout: 900
    wait: true
    wait_condition:
      type: Ready
      status: true
