# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Create user and assert it exists inside Keystone
  hosts: all
  tasks:
    - name: Get Keycloak PostgreSQL cluster
      run_once: true
      kubernetes.core.k8s_info:
        api_version: postgresql.cnpg.io/v1
        kind: Cluster
        name: keycloak-db
        namespace: auth-system
      register: _keycloak_postgresql_cluster

    - name: Assert Keycloak PostgreSQL cluster is ready
      run_once: true
      ansible.builtin.assert:
        that:
          - _keycloak_postgresql_cluster.resources | length == 1
          - _keycloak_postgresql_cluster.resources[0].spec.imageName is defined
          - _keycloak_postgresql_cluster.resources[0].spec.managed.roles[0].name == 'keycloak'
          - _keycloak_postgresql_cluster.resources[0].spec.managed.roles[0].passwordSecret.name == 'keycloak-db-user'
          - _keycloak_postgresql_cluster.resources[0].status.conditions | selectattr('type', 'equalto', 'Ready') | map(attribute='status') | list == ['True']

    - name: Get Keycloak database credentials
      run_once: true
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: keycloak-db-user
        namespace: auth-system
      register: _keycloak_database_credentials

    - name: Assert Keycloak database credentials exist
      run_once: true
      ansible.builtin.assert:
        that:
          - _keycloak_database_credentials.resources | length == 1
          - _keycloak_database_credentials.resources[0].type == 'kubernetes.io/basic-auth'
          - _keycloak_database_credentials.resources[0].metadata.labels['cnpg.io/reload'] == 'true'
          - _keycloak_database_credentials.resources[0].data.username is defined
          - _keycloak_database_credentials.resources[0].data.password is defined

    - name: Get Keycloak database
      run_once: true
      kubernetes.core.k8s_info:
        api_version: postgresql.cnpg.io/v1
        kind: Database
        name: keycloak
        namespace: auth-system
      register: _keycloak_database

    - name: Assert Keycloak database is ready
      run_once: true
      ansible.builtin.assert:
        that:
          - _keycloak_database.resources | length == 1
          - _keycloak_database.resources[0].spec.name == 'keycloak'
          - _keycloak_database.resources[0].spec.owner == 'keycloak'
          - _keycloak_database.resources[0].spec.cluster.name == 'keycloak-db'
          - _keycloak_database.resources[0].status.applied

    - name: Get Keycloak Operator CRDs
      run_once: true
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: "{{ item }}"
      loop:
        - keycloaks.k8s.keycloak.org
        - keycloakrealmimports.k8s.keycloak.org
      register: _keycloak_operator_crds

    - name: Assert Keycloak Operator CRDs are installed
      run_once: true
      ansible.builtin.assert:
        that:
          - _keycloak_operator_crds.results | map(attribute='resources') | map('length') | list == [1, 1]

    - name: Get Keycloak Operator deployment
      run_once: true
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: keycloak-operator
        namespace: auth-system
      register: _keycloak_operator_deployment

    - name: Assert Keycloak Operator is ready
      run_once: true
      ansible.builtin.assert:
        that:
          - _keycloak_operator_deployment.resources | length == 1
          - _keycloak_operator_deployment.resources[0].status.availableReplicas == 1

    - name: Create Keycloak user
      run_once: true
      delegate_to: localhost
      community.general.keycloak_user:
        # Keycloak settings
        auth_keycloak_url: "https://{{ keycloak_host }}"
        auth_realm: master
        auth_client_id: admin-cli
        auth_username: admin
        auth_password: "{{ keycloak_admin_password }}"
        validate_certs: "{{ cluster_issuer_type != 'self-signed' }}"
        # User settings
        realm: atmosphere
        username: test-user
      register: keycloak_user_result

    - name: Set a fact with user information using "end_state" or "existing"
      run_once: true
      ansible.builtin.set_fact:
        keycloak_user_info: "{{ keycloak_user_result.existing | ternary(keycloak_user_result.existing, keycloak_user_result.end_state) }}"

    - name: Get list of all users in "atmosphere" domain
      run_once: true
      delegate_to: localhost
      vexxhost.atmosphere.identity_user_info:
        domain: atmosphere
        name: "{{ keycloak_user_info.username }}"
      register: identity_user_info_result
      # XXX(mnaser): GHA seems to be slow so the user doesn't show up right
      #              away, it could also be a Keystone caching issue.  Poll
      #              less aggressively and give Keystone up to five minutes to
      #              see the federated Keycloak user.
      retries: 30
      delay: 10
      until: identity_user_info_result.users | length > 0

    - name: Assert that the user exists
      run_once: true
      ansible.builtin.assert:
        that:
          - identity_user_info_result.users | length > 0
          - identity_user_info_result.users[0].id == keycloak_user_info.id | regex_replace('-', '')
          - identity_user_info_result.users[0].name == keycloak_user_info.username

    # TODO: Simulate Keystone authentication
    # TODO: Simulate Horizon login
