VERSION 0.7

platform-image:
  ARG RELEASE=zed
  FROM ../cloud-archive-base+image --RELEASE=${RELEASE}
  LABEL org.opencontainers.image.source=https://github.com/vexxhost/atmosphere
  COPY keyrings/ceph.gpg /etc/apt/trusted.gpg.d/
  IF [ "$(lsb_release -sc)" = "focal" ]
    RUN echo "deb http://download.ceph.com/debian-quincy/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/ceph.list
  ELSE IF [ "$(lsb_release -sc)" = "jammy" ]
    RUN echo "deb http://download.ceph.com/debian-reef/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/ceph.list
  ELSE
    RUN echo "${RELEASE} is not supported on $(lsb_release -sc)"
    RUN exit 1
  END
  DO ../+APT_INSTALL --PACKAGES="ceph-common cgroup-tools dmidecode ebtables iproute2 ipxe-qemu kmod libvirt-clients libvirt-daemon-system openssh-client openvswitch-switch ovmf pm-utils qemu-block-extra qemu-efi qemu-kvm seabios"
  DO ../+CREATE_PROJECT_USER --PROJECT=nova
  SAVE IMAGE --push ghcr.io/vexxhost/atmosphere/libvirtd:${RELEASE}

image:
  BUILD --platform linux/amd64 --platform linux/arm64 +platform-image
