# Copyright (c) 2026 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# Base arguments for the OpenStack exporter.
openstack_exporter_args:
  - --endpoint-type
  - internal
  - default
  - --collect-metric-time
  - --disable-metric=cinder-agent_state
  - --disable-metric=cinder-limits_backup_max_gb
  - --disable-metric=cinder-limits_backup_used_gb
  - --disable-metric=cinder-limits_volume_max_gb
  - --disable-metric=cinder-limits_volume_used_gb
  - --disable-metric=cinder-snapshots
  - --disable-metric=cinder-volume_gb
  - --disable-metric=cinder-volume_status
  - --disable-metric=cinder-volume_status_counter
  - --disable-metric=cinder-volume_type_quota_gigabytes
  - --disable-metric=cinder-volumes
  - --disable-service.identity
  - --disable-service.image
  - --disable-service.placement
  - --disable-service.compute
  - --disable-service.object-store
  - --disable-service.load-balancer
  - --disable-service.container-infra
  - --disable-service.dns
  - --disable-service.baremetal
  - --disable-service.gnocchi
  - --disable-service.database
  - --disable-service.orchestration

# Neutron metrics to disable when using the OVN network backend.
openstack_exporter_neutron_disabled_metrics:
  - --disable-metric=neutron-l3_agent_of_router
  - --disable-metric=neutron-floating_ip
  - --disable-metric=neutron-floating_ips
  - --disable-metric=neutron-floating_ips_associated_not_active
  - --disable-metric=neutron-network
  - --disable-metric=neutron-network_ip_availabilities_total
  - --disable-metric=neutron-network_ip_availabilities_used
  - --disable-metric=neutron-networks
  - --disable-metric=neutron-port
  - --disable-metric=neutron-ports
  - --disable-metric=neutron-ports_lb_not_active
  - --disable-metric=neutron-ports_no_ips
  - --disable-metric=neutron-quota_floatingip
  - --disable-metric=neutron-quota_network
  - --disable-metric=neutron-quota_port
  - --disable-metric=neutron-quota_rbac_policy
  - --disable-metric=neutron-quota_router
  - --disable-metric=neutron-quota_security_group
  - --disable-metric=neutron-quota_security_group_rule
  - --disable-metric=neutron-quota_subnet
  - --disable-metric=neutron-quota_subnetpool
  - --disable-metric=neutron-router
  - --disable-metric=neutron-routers
  - --disable-metric=neutron-routers_not_active
  - --disable-metric=neutron-security_groups
  - --disable-metric=neutron-subnet
  - --disable-metric=neutron-subnets
