VERSION 0.7

image:
  ARG PROJECT=heat
  ARG RELEASE=zed
  ARG REF=a2b70a93658ecd2774f22c63a394c5629aefdbe7
  FROM ../openstack-service+image \
    --PROJECT ${PROJECT} \
    --RELEASE ${RELEASE} \
    --PROJECT_REF ${REF}
  DO \
    ../+APT_INSTALL \
    --PACKAGES "curl jq"
  DO ../+APPLY_PATCHES
  SAVE IMAGE --push \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${RELEASE} \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${REF}
