VERSION 0.7

image:
  ARG PROJECT=manila
  ARG RELEASE=zed
  ARG REF=9ea49e2b9df7da16d5700810eee18710dc90e6a4
  FROM ../openstack-service+image \
    --PROJECT ${PROJECT} \
    --RELEASE ${RELEASE} \
    --PROJECT_REF ${REF}
  DO \
    ../+APT_INSTALL \
    --PACKAGES "iproute2 openvswitch-switch"
  DO ../+APPLY_PATCHES
  SAVE IMAGE --push \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${RELEASE} \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${REF}
