VERSION 0.7

image:
  ARG PROJECT=manila
  ARG RELEASE=zed
  ARG REF=91e61299eab4497e38bd7a64e3365041a4d658fc
  FROM ../openstack-service+image \
    --PROJECT ${PROJECT} \
    --RELEASE ${RELEASE} \
    --PROJECT_REF ${REF}
  DO \
    ../+APT_INSTALL \
    --PACKAGES "iproute2 openvswitch-switch"
  DO ../+APPLY_PATCHES
  SAVE IMAGE --push \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${RELEASE} \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${REF}
