# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

_keycloak_database_migration_export_env:
  - name: KC_DB
    value: mysql
  - name: KC_DB_URL
    value: "jdbc:mysql://{{ keycloak_database_migration_source_host }}:{{ keycloak_database_migration_source_port }}/{{ keycloak_database_migration_source_name }}"
  - name: KC_DB_USERNAME
    value: "{{ keycloak_database_migration_source_username }}"
  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ keycloak_database_migration_source_secret_name }}"
        key: "{{ keycloak_database_migration_source_secret_key }}"
  - name: KC_TRANSACTION_XA_ENABLED
    value: "false"

_keycloak_database_migration_import_env:
  - name: KC_DB
    value: postgres
  - name: KC_DB_URL
    value: "jdbc:postgresql://{{ keycloak_database_migration_target_host }}:{{ keycloak_database_migration_target_port }}/{{ keycloak_database_migration_target_name }}"
  - name: KC_DB_USERNAME
    value: "{{ keycloak_database_migration_target_username }}"
  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ keycloak_database_migration_target_secret_name }}"
        key: "{{ keycloak_database_migration_target_secret_key }}"
  - name: KC_TRANSACTION_XA_ENABLED
    value: "false"
