VERSION 0.7

image:
  FROM curlimages/curl:7.78.0
  RUN curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/${TARGETOS}/${TARGETARCH}/kubectl" -o /tmp/kubectl
  RUN chmod +x /tmp/kubectl
  SAVE ARTIFACT /tmp/kubectl kubectl
