#!/bin/bash -xe

for RELEASE in $(ls -1 images/openstack/releases); do
  BRANCH=$(cat images/openstack/releases/${RELEASE}/branch)

  for PROJECT in $(ls -1 images/openstack/projects); do
    mkdir -p images/openstack/projects/${PROJECT}/${RELEASE}
    curl -s https://opendev.org/api/v1/repos/openstack/${PROJECT}/branches/${BRANCH} | jq -r '.commit.id' > projects/${PROJECT}/${RELEASE}/ref
  done
done
