VERSION 0.7

ARG --global CAPO_VERSION=v0.8.0
ARG --global EPOCH=2

clone:
  FROM ../builder+image
  GIT CLONE --branch ${CAPO_VERSION} https://github.com/kubernetes-sigs/cluster-api-provider-openstack /workspace/src
  WORKDIR /workspace/src
  COPY patches /workspace/patches
  RUN git apply --verbose /workspace/patches/*.patch
  SAVE ARTIFACT /workspace/src

image:
  FROM DOCKERFILE -f +clone/src/Dockerfile +clone/src/*
  LABEL org.opencontainers.image.source=https://github.com/vexxhost/atmosphere
  ARG REGISTRY=ghcr.io/vexxhost/atmosphere
  SAVE IMAGE --push ${REGISTRY}/capi-openstack-controller:${CAPO_VERSION}-${EPOCH}
