VERSION 0.7

image:
  ARG PROJECT=placement
  ARG RELEASE=zed
  ARG REF=d7ced6bd2fc82caf458f20b5652888164b1bbb70
  FROM ../openstack-service+image \
    --PROJECT ${PROJECT} \
    --RELEASE ${RELEASE} \
    --PROJECT_REF ${REF}
  SAVE IMAGE --push \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${RELEASE} \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${REF}
