VERSION 0.7

image:
  FROM ubuntu:jammy-20240125
  LABEL org.opencontainers.image.source=https://github.com/vexxhost/atmosphere
  # CVE-2023-5678, CVE-2023-6129, CVE-2023-6237, CVE-2024-0727
  DO ../+APT_INSTALL --PACKAGES "libssl3=3.0.2-0ubuntu1.14"
