VERSION 0.7

image:
  FROM ubuntu:jammy-20240111
  LABEL org.opencontainers.image.source=https://github.com/vexxhost/atmosphere
  # TODO(mnaser): Remove this when a new image that includes 1.4.0-11ubuntu2.4 is released.
  #               https://avd.aquasec.com/nvd/cve-2024-22365
  DO ../+APT_INSTALL \
    --PACKAGES "libpam0g libpam-modules libpam-modules-bin libpam-runtime"
