---
# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

host_libvirt_sockets_enabled: true

host_libvirt_sockets_units:
  - libvirtd.service
  - libvirtd.socket
  - libvirtd-ro.socket
  - libvirtd-admin.socket
  - libvirtd-tcp.socket
  - libvirtd-tls.socket
  - virtlogd.service
  - virtlogd.socket
  - virtlockd.service
  - virtlockd.socket
  - virtqemud.service
  - virtqemud.socket
  - virtqemud-ro.socket
  - virtqemud-admin.socket
  - virtproxyd.service
  - virtproxyd.socket
  - virtproxyd-ro.socket
  - virtproxyd-admin.socket
