VERSION 0.7

ARG --global REGISTRY=ghcr.io/vexxhost/atmosphere
ARG --global PROJECT=ironic
ARG --global RELEASE=zed
ARG --global PROJECT_REF=e38735cb95263b0c54f2fd719ff6b714efbddbb3

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF} \
    --PIP_PACKAGES "python-dracclient sushy"

image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  DO ../+APT_INSTALL \
    --PACKAGES "ethtool ipmitool iproute2 ipxe lshw qemu-utils tftpd-hpa"
  SAVE IMAGE --push \
    ${REGISTRY}/${PROJECT}:${RELEASE} \
    ${REGISTRY}/${PROJECT}:${PROJECT_REF}
