VERSION 0.7

ARG --global RELEASE=zed
ARG --global PROJECT=barbican
ARG --global PROJECT_REF=7d6749fcb1ad16a3350de82cd8e523d5b55306f8

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF}
    --PIP_PACKAGES "pykmip"

image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  SAVE IMAGE --push \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${RELEASE} \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${PROJECT_REF}
