VERSION 0.7

image:
  ARG PROJECT=barbican
  ARG RELEASE=zed
  ARG REF=7d6749fcb1ad16a3350de82cd8e523d5b55306f8
  FROM ../openstack-service+image \
    --PROJECT ${PROJECT} \
    --RELEASE ${RELEASE} \
    --PROJECT_REF ${REF} \
    --PIP_PACKAGES "pykmip"
  DO ../+APPLY_PATCHES
  SAVE IMAGE --push \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${RELEASE} \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${REF}
