{
 "title": "OpenStack Libvirt VM",
 "description": "This is complete dashboard to monitor libvirt hypervisors and virtual machines",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "vm uuid", "query": { "query": "label_values(uuid)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "VM CPU load ",
   "type": "timeseries",
   "description": "CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(libvirtd_domain_vcpu_time{uuid=~\"$instance.*\"}[5m]) /1000000000",
     "legendFormat": "vcpu"
    }
   ]
  },
  {
   "title": "Memory Stats ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available memory inside vm",
   "type": "timeseries",
   "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "libvirtd_domain_balloon_usable{uuid=~\"$instance.*\"}",
     "legendFormat": "({{uuid}})"
    }
   ]
  },
  {
   "title": "Total memory inside vm",
   "type": "timeseries",
   "description": "The total amount of usable memory as seen by the domain. This value may be less than the amount of memory assigned to the domain if a balloon driver is in use or if the guest OS does not initialize all assigned pages. This value is expressed in kB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "libvirtd_domain_balloon_maximum{uuid=~\"$instance.*\"}",
     "legendFormat": "({{uuid}})"
    }
   ]
  },
  {
   "title": "Major fault",
   "type": "timeseries",
   "description": "Page faults occur when a process makes a valid access to virtual memory that is not available. When servicing the page fault, if disk IO is required, it is considered a major fault.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libvirtd_domain_balloon_major_fault{uuid=~\"$instance.*\"}",
     "legendFormat": "({{uuid}})"
    }
   ]
  },
  {
   "title": "Minor fault",
   "type": "timeseries",
   "description": "Page faults occur when a process makes a valid access to virtual memory that is not available. When servicing the page not fault, if disk IO is required, it is considered a minor fault.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libvirtd_domain_balloon_minor_fault{uuid=~\"$instance.*\"}",
     "legendFormat": "({{uuid}})"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "description": "The amount of memory, that can be quickly reclaimed without additional I/O (in kB).Typically these pages are used for caching files from disk.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "libvirtd_domain_balloon_disk_caches{uuid=~\"$instance.*\"}",
     "legendFormat": "({{uuid}})"
    }
   ]
  },
  {
   "title": "Interface Stats ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "Number of bytes transmitted on a network interface, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(libvirtd_domain_net_rx_bytes{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}} - receive"
    },
    {
     "expr": "irate(libvirtd_domain_net_tx_bytes{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{ uuid }} - transfer"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "description": "Number of packets received on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(libvirtd_domain_net_tx_packets{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}} - receive"
    },
    {
     "expr": "rate(libvirtd_domain_net_rx_packets{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}} - transfer"
    }
   ]
  },
  {
   "title": "Network drops",
   "type": "timeseries",
   "description": "Number of packet transmit drops on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libvirtd_domain_net_rx_drop{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}} - receive"
    },
    {
     "expr": "rate(libvirtd_domain_net_tx_drop{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{ uuid }} - transfer"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "description": "Number of packet receive errors on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libvirtd_domain_net_tx_errors{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}} - receive"
    },
    {
     "expr": "rate(libvirtd_domain_net_rx_errors{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}} - transmit"
    }
   ]
  },
  {
   "title": "Block Stats (by instance and domain)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Write and read requests",
   "type": "timeseries",
   "description": "Number of write requests to a block device.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(libvirtd_domain_block_write_requests{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}} - write"
    },
    {
     "expr": "irate(libvirtd_domain_block_read_requests{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}} - read"
    }
   ]
  },
  {
   "title": "Write and read time",
   "type": "timeseries",
   "description": "Total time (ns) spent on writes on a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "irate(libvirtd_domain_block_write_times{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}} - write"
    },
    {
     "expr": "irate(libvirtd_domain_block_read_times{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}} - read"
    }
   ]
  },
  {
   "title": "Write and read bytes",
   "type": "timeseries",
   "description": "Number of bytes written to a block device, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(libvirtd_domain_block_write_bytes{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{ uuid }} - write"
    },
    {
     "expr": "irate(libvirtd_domain_block_read_bytes{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{ uuid }} - read"
    }
   ]
  },
  {
   "title": "Flush requests",
   "type": "timeseries",
   "description": "Total flush requests from a block device.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(libvirtd_domain_block_flush_times{uuid=~\"$instance.*\"}[5m])",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}