# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- hosts: all
  become: true
  tasks:
    - name: Install "jq" for log collection
      ansible.builtin.apt:
        name: jq
        update_cache: true
      when:
        - ansible_facts['os_family'] | lower == 'debian'

    - name: Install pip3 for Python package management
      ansible.builtin.apt:
        name: python3-pip
      when:
        - ansible_facts['os_family'] | lower == 'debian'

    - name: Install Python "kubernetes" library for kubernetes.core modules
      ansible.builtin.pip:
        name: kubernetes

- hosts: all
  roles:
    - role: ensure-go
      go_version: "1.24.4"

- hosts: all
  tasks:
    - name: Build atmosphere binary
      ansible.builtin.command:
        cmd: go build -o ./bin/atmosphere ./cmd/atmosphere
        chdir: "{{ zuul.project.src_dir }}"
      delegate_to: localhost
      run_once: true
      changed_when: false
      environment:
        CGO_ENABLED: "0"
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH | default(lookup('env', 'PATH')) }}"
