VERSION 0.7

image:
  ARG PROJECT=glance
  ARG RELEASE=zed
  ARG REF=06a18202ab52c64803f044b8f848ed1c160905d2
  ARG PACKAGES="ceph-common lsscsi nvme-cli python3-rados python3-rbd qemu-utils sysfsutils udev util-linux"
  ARG PIP_PACKAGES="glance_store[cinder]"
  FROM ../openstack-service+image --PROJECT ${PROJECT} --RELEASE ${RELEASE} --PROJECT_REF ${REF} --PACKAGES "${PACKAGES}" --PIP_PACKAGES "${PIP_PACKAGES}"
  COPY ../kubernetes+image/kubectl /usr/local/bin/kubectl
  SAVE IMAGE --push \
    ghcr.io/vexxhost/atmosphere/glance:${RELEASE} \
    ghcr.io/vexxhost/atmosphere/glance:${REF}
