VERSION 0.7

ARG --global REGISTRY=ghcr.io/vexxhost/atmosphere
ARG --global PROJECT=glance
ARG --global RELEASE=2023.2
ARG --global PROJECT_REF=9a4a3067b5c7c7f8ee9363bd939a3d86b260d660

build.plugin:
  ARG PLUGIN
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+GIT_CHECKOUT \
    --PROJECT=${PLUGIN} \
    --PROJECT_REF=stable/${RELEASE}
  SAVE ARTIFACT /src

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  COPY (+build.plugin/src --PLUGIN=glance_store) /glance_store
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF} \
    --PIP_PACKAGES="/glance_store[cinder]"

image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  COPY ../kubernetes+image/kubectl /usr/local/bin/kubectl
  DO ../+APT_INSTALL \
    --PACKAGES "ceph-common lsscsi nvme-cli python3-rados python3-rbd qemu-utils sysfsutils udev util-linux"
  SAVE IMAGE --push \
    ${REGISTRY}/${PROJECT}:${RELEASE} \
    ${REGISTRY}/${PROJECT}:${PROJECT_REF}
