# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Generate Loki alert rule files
  ansible.builtin.set_fact:
    _loki_alert_rule_files: "{{ _loki_default_alert_rule_files | combine(loki_alert_rule_files, recursive=True) }}"

- name: Ensure Loki namespace exists
  run_once: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ loki_helm_kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ loki_helm_release_namespace }}"

- name: Create Loki alert rules ConfigMap
  run_once: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ loki_helm_kubeconfig }}"
    definition: "{{ _loki_alert_rules_configmap | combine({'data': _loki_alert_rule_files}, recursive=True) }}"

- name: Deploy Helm chart
  run_once: true
  kubernetes.core.helm:
    name: "{{ loki_helm_release_name }}"
    chart_ref: "{{ loki_helm_chart_ref }}"
    release_namespace: "{{ loki_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: "{{ loki_helm_kubeconfig }}"
    values: "{{ _loki_helm_values | combine(loki_helm_values, recursive=True) | to_json }}"
