annotations:
  artifacthub.io/category: storage
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Release Highlights
      url: https://scod.hpedev.io/csi_driver/index.html#latest_release
    - name: Release Notes
      url: https://github.com/hpe-storage/csi-driver/tree/master/release-notes
    - name: Documentation
      url: https://scod.hpedev.io/csi_driver
    - name: Chart Source
      url: https://github.com/hpe-storage/co-deployments
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/olm/community-operators/hpe-csi-operator
    - url: https://artifacthub.io/packages/helm/hpe-storage/hpe-csi-info-metrics
    - url: https://artifacthub.io/packages/helm/hpe-storage/hpe-array-exporter
apiVersion: v1
appVersion: 3.1.0
description: A Helm chart for installing the HPE CSI Driver for Kubernetes
home: https://hpe.com/storage/containers
icon: https://raw.githubusercontent.com/hpe-storage/co-deployments/master/docs/assets/hpedev.png
keywords:
- HPE
- Storage
- CSI
maintainers:
- email: dev-hi-containers@hpe.com
  name: datamattsson
name: hpe-csi-driver
sources:
- https://github.com/hpe-storage/csi-driver
version: 3.1.0
