VERSION 0.7

APT_INSTALL:
  COMMAND
  ARG PACKAGES
  RUN \
    apt-get update && \
    apt-get install --no-install-recommends -y ${PACKAGES} && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
