apiVersion: v2
appVersion: 2.0.0
description: Cert-manager webhook for interacting with InfoBlox WAPI servers
home: https://github.com/sarg3nt/cert-manager-webhook-infoblox-wapi
keywords:
- cert-manager
- webhook
- letsencrypt
- acme
- dns01
- infoblox
maintainers:
- email: dave@sarg3.net
  name: Dave Sargent
name: cert-manager-webhook-infoblox-wapi
sources:
- https://github.com/sarg3nt/cert-manager-webhook-infoblox-wapi
type: application
version: 2.0.0
