# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

_hpe_nimble_csi_helm_values:
  disable:
    nimble: false
    alletra6000: true
    primera: true
    alletra9000: true
    alletraStorageMP: true
    b10000FileService: true
  images:
    csiControllerDriver: "{{ atmosphere_images['hpe_csi_controller_driver'] }}"
    csiNodeDriver: "{{ atmosphere_images['hpe_csi_node_driver'] }}"
    nimbleCSP: "{{ atmosphere_images['hpe_csi_nimble_csp'] }}"
    nfsProvisioner: "{{ atmosphere_images['hpe_csi_nfs_provisioner'] }}"
    csiExtensions: "{{ atmosphere_images['hpe_csi_extensions'] }}"
    csiVolumeGroupProvisioner: "{{ atmosphere_images['hpe_csi_volume_group_provisioner'] }}"
    csiVolumeGroupSnapshotter: "{{ atmosphere_images['hpe_csi_volume_group_snapshotter'] }}"
    csiVolumeMutator: "{{ atmosphere_images['hpe_csi_volume_mutator'] }}"
    csiAttacher: "{{ atmosphere_images['hpe_csi_attacher'] }}"
    csiNodeDriverRegistrar: "{{ atmosphere_images['hpe_csi_node_driver_registrar'] }}"
    csiProvisioner: "{{ atmosphere_images['hpe_csi_provisioner'] }}"
    csiResizer: "{{ atmosphere_images['hpe_csi_resizer'] }}"
    csiSnapshotter: "{{ atmosphere_images['hpe_csi_snapshotter'] }}"
