#!/usr/bin/env python3

import glob
import sys
import json

releases = sorted([r.split("/")[-1] for r in glob.glob("images/openstack/releases/*")])
projects = sorted([r.split("/")[-1] for r in glob.glob("images/openstack/projects/*")])

matrix = {
    "release": releases,
    "project": projects,
}

json.dump(
    matrix,
    sys.stdout,
    separators=(",", ":"),
)
