#!/usr/bin/env python3

import glob
import json
import requests
import sys

MATRIX = []

RELEASES = sorted([r.split("/")[-1] for r in glob.glob("images/openstack/releases/*")])
PROJECTS = sorted([r.split("/")[-1] for r in glob.glob("images/openstack/projects/*")])

for release in RELEASES:
    for project in PROJECTS:
        ref = (
            open(f"images/openstack/projects/{project}/{release}/ref", "r")
            .read()
            .strip()
        )

        r = requests.get(
            f"https://quay.io/api/v1/repository/vexxhost/{project}/tag/?specificTag={ref}"
        )

        if r.json().get("tags") == []:
            MATRIX += [
                {
                    "release": release,
                    "project": project,
                }
            ]

DATA = None
if len(MATRIX) != 0:
    DATA = {
        "release": [],
        "project": [],
        "include": MATRIX,
    }

json.dump(DATA, sys.stdout, separators=(",", ":"))
