VERSION 0.7

image:
  FROM ../base+image
  DO ../+APT_INSTALL --packages "build-essential git python3-dev python3-pip python3-venv"
  ARG POETRY_VERSION=1.4.2
  RUN pip3 install --no-cache-dir poetry==${POETRY_VERSION}
