VERSION 0.7

ARG --global RELEASE=zed
ARG --global PROJECT=neutron
ARG --global PROJECT_REF=222c997022392561c2de2cb493f0f5214eb20dfc

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF} \
    --PIP_PACKAGES="git+https://github.com/openstack/neutron-vpnaas.git@256464aea691f8b4957ba668a117963353f34e4c"

platform-image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  DO ../+APT_INSTALL \
    --PACKAGES "conntrack dnsmasq dnsmasq-utils ebtables ethtool haproxy iproute2 ipset iptables iputils-arping jq keepalived lshw openvswitch-switch strongswan uuid-runtime"
  SAVE IMAGE --push \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${RELEASE} \
    ghcr.io/vexxhost/atmosphere/${PROJECT}:${PROJECT_REF}

image:
  BUILD --platform linux/amd64 --platform linux/arm64 +platform-image
