VERSION 0.7

binary:
  FROM curlimages/curl:7.78.0
  ARG TARGETOS
  ARG TARGETARCH
  ARG VERSION=3.14.0
  WORKDIR /tmp
  RUN curl -LO https://get.helm.sh/helm-v3.14.0-${TARGETOS}-${TARGETARCH}.tar.gz
  RUN tar -zxvf /tmp/helm-v3.14.0-${TARGETOS}-${TARGETARCH}.tar.gz
  RUN ${TARGETOS}-${TARGETARCH}/helm version
  SAVE ARTIFACT ${TARGETOS}-${TARGETARCH}/helm
