VERSION 0.8

ARG --global PROJECT=python-openstackclient
ARG --global RELEASE=2023.2
ARG --global PROJECT_REF=41381c80b5f3583639a9cd9bab6d208684112fd7

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF} \
    --PIP_PACKAGES="python-barbicanclient python-designateclient python-glanceclient python-heatclient python-magnumclient python-manilaclient python-neutronclient python-octaviaclient osc-placement python-senlinclient python-swiftclient"

image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  ARG REGISTRY=ghcr.io/vexxhost/atmosphere
  SAVE IMAGE --push \
    ${REGISTRY}/${PROJECT}:${RELEASE} \
    ${REGISTRY}/${PROJECT}:${PROJECT_REF}
