VERSION 0.7

ARG --global PROJECT=horizon
ARG --global RELEASE=2023.2
ARG --global PROJECT_REF=e9bf695641f4c07fadacf12599ae406c5ecd3ca6

build.plugin:
  ARG PLUGIN
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+GIT_CHECKOUT \
    --PROJECT=${PLUGIN} \
    --PROJECT_REF=stable/${RELEASE}
  SAVE ARTIFACT /src

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  COPY (+build.plugin/src --PLUGIN=designate-dashboard) /designate-dashboard
  COPY (+build.plugin/src --PLUGIN=heat-dashboard) /heat-dashboard
  COPY (+build.plugin/src --PLUGIN=ironic-ui) /ironic-ui
  COPY (+build.plugin/src --PLUGIN=magnum-ui) /magnum-ui
  COPY (+build.plugin/src --PLUGIN=manila-ui) /manila-ui
  COPY (+build.plugin/src --PLUGIN=neutron-vpnaas-dashboard) /neutron-vpnaas-dashboard
  COPY (+build.plugin/src --PLUGIN=octavia-dashboard) /octavia-dashboard
  COPY (+build.plugin/src --PLUGIN=senlin-dashboard) /senlin-dashboard
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF} \
    --PIP_PACKAGES "/designate-dashboard /heat-dashboard /ironic-ui /magnum-ui /neutron-vpnaas-dashboard /octavia-dashboard /senlin-dashboard /manila-ui"

image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  DO ../+APT_INSTALL \
    --PACKAGES "apache2 gettext libapache2-mod-wsgi-py3"
  ARG REGISTRY=ghcr.io/vexxhost/atmosphere
  SAVE IMAGE --push \
    ${REGISTRY}/${PROJECT}:${RELEASE} \
    ${REGISTRY}/${PROJECT}:${PROJECT_REF}
