# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

# List of Helm charts to upload.
#
# upload_helm_charts_list:
#   - src: "../../charts/neutron/"
#     dest: "/usr/local/src/neutron"
upload_helm_charts_list:
  - src: "../../charts/barbican/"
    dest: "/usr/local/src/barbican"
  - src: "../../charts/ceph-csi-rbd/"
    dest: "/usr/local/src/ceph-csi-rbd"
  - src: "../../charts/ceph-provisioners/"
    dest: "/usr/local/src/ceph-provisioners"
  - src: "../../charts/cinder/"
    dest: "/usr/local/src/cinder"
  - src: "../../charts/coredns/"
    dest: "/usr/local/src/coredns"
  - src: "../../charts/designate/"
    dest: "/usr/local/src/designate"
  - src: "../../charts/frr-k8s/"
    dest: "/usr/local/src/frr-k8s"
  - src: "../../charts/glance/"
    dest: "/usr/local/src/glance"
  - src: "../../charts/godaddy-webhook/"
    dest: "/usr/local/src/godaddy-webhook"
  - src: "../../charts/goldpinger/"
    dest: "/usr/local/src/goldpinger"
  - src: "../../charts/heat/"
    dest: "/usr/local/src/heat"
  - src: "../../charts/horizon/"
    dest: "/usr/local/src/horizon"
  - src: "../../charts/ingress-nginx/"
    dest: "/usr/local/src/ingress-nginx"
  - src: "../../charts/ironic/"
    dest: "/usr/local/src/ironic"
  - src: "../../charts/keycloak/"
    dest: "/usr/local/src/keycloak"
  - src: "../../charts/keystone/"
    dest: "/usr/local/src/keystone"
  - src: "../../charts/kube-prometheus-stack/"
    dest: "/usr/local/src/kube-prometheus-stack"
  - src: "../../charts/libvirt/"
    dest: "/usr/local/src/libvirt"
  - src: "../../charts/local-path-provisioner/"
    dest: "/usr/local/src/local-path-provisioner"
  - src: "../../charts/loki/"
    dest: "/usr/local/src/loki"
  - src: "../../charts/magnum/"
    dest: "/usr/local/src/magnum"
  - src: "../../charts/manila/"
    dest: "/usr/local/src/manila"
  - src: "../../charts/memcached/"
    dest: "/usr/local/src/memcached"
  - src: "../../charts/neutron/"
    dest: "/usr/local/src/neutron"
  - src: "../../charts/node-feature-discovery/"
    dest: "/usr/local/src/node-feature-discovery"
  - src: "../../charts/nova/"
    dest: "/usr/local/src/nova"
  - src: "../../charts/octavia/"
    dest: "/usr/local/src/octavia"
  - src: "../../charts/openvswitch/"
    dest: "/usr/local/src/openvswitch"
  - src: "../../charts/ovn/"
    dest: "/usr/local/src/ovn"
  - src: "../../charts/placement/"
    dest: "/usr/local/src/placement"
  - src: "../../charts/prometheus-pushgateway/"
    dest: "/usr/local/src/prometheus-pushgateway"
  - src: "../../charts/pxc-operator/"
    dest: "/usr/local/src/pxc-operator"
  - src: "../../charts/rabbitmq-cluster-operator/"
    dest: "/usr/local/src/rabbitmq-cluster-operator"
  - src: "../../charts/rook-ceph/"
    dest: "/usr/local/src/rook-ceph"
  - src: "../../charts/rook-ceph-cluster/"
    dest: "/usr/local/src/rook-ceph-cluster"
  - src: "../../charts/staffeln/"
    dest: "/usr/local/src/staffeln"
  - src: "../../charts/tempest/"
    dest: "/usr/local/src/tempest"
  - src: "../../charts/valkey/"
    dest: "/usr/local/src/valkey"
  - src: "../../charts/vector/"
    dest: "/usr/local/src/vector"

# Number of retries for each chart upload.
upload_helm_charts_retries: 3

# Delay between retries in seconds.
upload_helm_charts_retry_delay: 5
