# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: run atmosphere-bond0-setup
  ansible.builtin.command: /usr/local/sbin/atmosphere-bond0-setup
  changed_when: false
