name: pr

on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled

permissions: {}

jobs:
  reno:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-release-notes')"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: step-security/changed-files@60967b822d3001fa82242f8d6b4ed46bc3600a68 # v47.0.1
        id: changed-files
        with:
          dir_names: true
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        if: "!contains(steps.changed-files.outputs.added_files, 'releasenotes/notes')"
        with:
          script: |
            core.setFailed("Pull requests without the 'skip-release-notes' label must add a release note with reno.")
